name: julianblau
favicon: null
layout_spectrum: 0.8911576215177774
typography_spectrum: 0.03982350113801658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6999108949676156
  lightness: 0.38239419204182923
  saturation: 0.5208972415421158
  rhythmicContrast: 0.3164697755128145
purpose: []
